spring:
  application:
    name: desafioEstagioJavaBackEnd_EnosRocha

  datasource:
    url: jdbc:mysql://localhost:3310/tarefaChallenge
    username: root
    password: Enos!2486
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8080